### PR TITLE
handle unhandled promise rejections with node 16

### LINKED ISSUE #271: Bot restarts on unhandled discord API-errors after upgrade to node 16 in upgrade-to-v13 branch
## Describe the bug
The bot restarts on unhandled discord API-errors after upgrade to node 16 in upgrade-to-v13 branch. In node v14 and our previous bot, these errors did not cause a crash and reboot of the bot. A relatively large surface of the code has promise code (using the discord.js library) that is not wrapped in try/catch blocks. This is related to how node has changed the handling of unhandled rejected promises since node v15.

## Expected behavior
Server should not reboot due to discord API errors which seems like a kind of error that can to some degree be expected.

## To Reproduce
Start the bot under the upgrade-to-v13 branch. Create an error in one of the commands. One way to trigger such an error is to remove the argument to the .send method in the command and then run the command.

## Additional context
Discord.js guide shows similar error handling here: https://discordjs.guide/popular-topics/errors.html#how-to-diagnose-api-errors
We are adding a notification of the error to a channel where they can be seen by bot developers

### PR DESCRIPTION
**Pull request by mikejoh12**
## What issue is this solving?

Closes #271

### Description
Adds global error handling for unhandled promise rejections in order to avoid server crash on these errors. Also sends an some error info in a channel to bot developers.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? No
- Any new dependencies to install? No

### Please make sure you've attempted to meet the following coding standards
- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -31,4 +31,20 @@ client.on('messageCreate', messageHandler);
 
 client.on('messageDelete', logDeletedMessages);
 
+process.on('unhandledRejection', async (error) => {
```
Comment (lyallstewart) [inline app.js:34]: In order to keep things nice and tidy, I think it may be best to follow the pattern in the other handlers and move this to it's own file in the `./handlers` folder then import and reference it here.

**Review by lyallstewart — CHANGES_REQUESTED** [review]
Looks good to me! 🔥 

Just one small thing I think we should do before merging.

File: app.js (hunk 1 above)
Comment (mikejoh12) [reply app.js]: Good idea. I restructured it like you suggested in the latest commit.

**Review by aedwardg — COMMENTED** [review]
@mikejoh12 I think this is great! The only change I would make is to put the resulting error post in an embed and style it a little, particularly if we include the path, method and httpStatus as discussed in the development server.

**Review by aedwardg — APPROVED** [review]
This change is :fire:

**Review by Victoria-DR — APPROVED** [review]
Looks great, thanks!

**Review by lyallstewart — APPROVED** [review]
Looks good to me, thanks for doing this!
